apiVersion: apps/v1
kind: Deployment
metadata:
  name: appseai-docs
  namespace: appseai-wfa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appseai-docs
  template:
    metadata:
      labels:
        app: appseai-docs
    spec:
      containers:
        - name: appseai-docs
          image: appseaiacr.azurecr.io/appseai-doc:latest  # <-- your image here
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "100m"