apiVersion: v1
kind: Service
metadata:
  name: appseai-docs
  namespace: appseai-wfa
spec:
  selector:
    app: appseai-docs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer